### ISSUE TITLE
使用gstreamer发生异常，这个是什么原因？

### ISSUE THREAD

**Issue by bxxmwys** [YueChen-C/ios-screen-record#11]
使用udp或录制文件功能正常。但是使用gstreamer就报错，这个是什么原因？
环境：macOS Monterey 12.3.1 gstreamer 1.20.1

![image](https://user-images.githubusercontent.com/7778311/166232620-0ff4fe38-0f84-408e-bd20-f6dd8e87abf0.png)

`
$ python3 main.py --udid=d9109d1133548f70456c8c150a63cdc610a6ddd8 gstreamer
2022-05-02 20:06:17,642 - util.py[line:58] - INFO: Find Device UDID: d9109d1133548f70456c8c150a63cdc610a6ddd8
2022-05-02 20:06:17,731 - gstreamer.py[line:124] - INFO: Starting Gstreamer..
Traceback (most recent call last):
  File "/Users/weiyansheng/work/Owner/ios-screen-record/ioscreen/main.py", line 60, in <module>
    main()
  File "/Users/weiyansheng/work/Owner/ios-screen-record/ioscreen/main.py", line 56, in main
    args.func(args)
  File "/Users/weiyansheng/work/Owner/ios-screen-record/ioscreen/main.py", line 28, in cmd_record_gstreamer
    consumer = GstAdapter.new(stopSignal)
  File "/usr/local/lib/python3.9/site-packages/ioscreen/coremedia/gstreamer.py", line 126, in new
    videoAppSrc = setup_video_pipeline(pipe)
  File "/usr/local/lib/python3.9/site-packages/ioscreen/coremedia/gstreamer.py", line 27, in setup_video_pipeline
    src.set_property("is-live", True)
AttributeError: 'NoneType' object has no attribute 'set_property'
`

**Comment by YueChen-C** [comment]
安装 gstreamer 了吗？根据 readme 里面流程安装 gstreamer

**Comment by bxxmwys** [comment]
> 安装 gstreamer 了吗？根据 readme 里面流程安装 gstreamer

安装了，按流程走的。gstreamer 1.20.1

![image](https://user-images.githubusercontent.com/7778311/167074018-dce8fa2c-549b-43af-b82b-ec9c0da87ab8.png)

**Comment by YueChen-C** [comment]
gst 插件呢，看起来是 src = Gst.ElementFactory.make("appsrc", "my-video_src") 初始化就失败了

`brew install gstreamer gst-plugins-bad gst-plugins-good gst-plugins-base gst-plugins-ugly`

**Comment by bxxmwys** [comment]
> gst 插件呢，看起来是 src = Gst.ElementFactory.make("appsrc", "my-video_src") 初始化就失败了
> 
> `brew install gstreamer gst-plugins-bad gst-plugins-good gst-plugins-base gst-plugins-ugly`

都有的，但依旧是出错了。

![image](https://user-images.githubusercontent.com/7778311/167240260-af71915e-2893-4caf-b3c3-2e3344c4f341.png)

**Comment by YueChen-C** [comment]
你可以运行的时候设置临时环境变量 GST_DEBUG=*:4 ， 运行的时候看看 gst 有什么明显报错没有 
`export GST_DEBUG=*:4`

**Comment by bxxmwys** [comment]
> 你可以运行的时候设置临时环境变量 GST_DEBUG=*:4 ， 运行的时候看看 gst 有什么明显报错没有
> `export GST_DEBUG=*:4`

![image](https://user-images.githubusercontent.com/7778311/167248061-8b53f5b8-1ff6-4a83-b1d7-6ee23d0cd4be.png)

**Comment by truebit** [comment]
GST_PLUGIN_PATH=/usr/local/lib/gstreamer-1.0
