### ISSUE TITLE
ubuntu 下不能使用

### ISSUE THREAD

**Issue by railsfans** [YueChen-C/ios-screen-record#13]
我在ubuntu 20.04下安装pip install ioscreen ;连接iphone6s手机，执行出现如下错误，这个是怎么回事。
root@ubuntu:~/Downloads$ ~/.local/bin/ioscreen --udid=4e50da4c5b930e51d8a37f8ec407864aea9d800c record -h264File=/home/root/a.h264 -wavFile=/home/root/b.wav
2022-08-24 04:53:58,087 - util.py[line:58] - INFO: Find Device UDID: 4e50da4c5b930e51d8a37f8ec407864aea9d800c
2022-08-24 04:53:58,088 - util.py[line:91] - INFO: Disabling hidden QT config
Traceback (most recent call last):
  File "/home/root/.local/bin/ioscreen", line 8, in <module>
    sys.exit(main())
  File "/home/root/.local/lib/python3.8/site-packages/ioscreen/main.py", line 56, in main
    args.func(args)
  File "/home/root/.local/lib/python3.8/site-packages/ioscreen/main.py", line 12, in cmd_record_wav
    start_reading(consumer, device, stopSignal)
  File "/home/root/.local/lib/python3.8/site-packages/ioscreen/util.py", line 152, in start_reading
    device.set_configuration()
  File "/home/root/.local/lib/python3.8/site-packages/usb/core.py", line 905, in set_configuration
    self._ctx.managed_set_configuration(self, configuration)
  File "/home/root/.local/lib/python3.8/site-packages/usb/core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "/home/root/.local/lib/python3.8/site-packages/usb/core.py", line 159, in managed_set_configuration
    self.backend.set_configuration(self.handle, cfg.bConfigurationValue)
  File "/home/root/.local/lib/python3.8/site-packages/usb/backend/libusb1.py", line 812, in set_configuration
    _check(self.lib.libusb_set_configuration(dev_handle.handle, config_value))
  File "/home/root/.local/lib/python3.8/site-packages/usb/backend/libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 16] Resource busy

**Comment by pansionpan** [comment]
问题有解决么

**Comment by railsfans** [comment]
没，你也遇到相同问题么

**Comment by pansionpan** [comment]
> 

是的，问题似乎出现在device.set_configuration上

**Comment by railsfans** [comment]
我找了另一个开源的库，https://github.com/danielpaulus/quicktime_video_hack，ubuntu下还是不行，同样在device.configure那边报错。

**Comment by pansionpan** [comment]
如果着急使用的话可以尝试使用imageio结合WDA的mjpeg server录屏的思路，代码在[这里](https://github.com/alibaba/taobao-iphone-device/blob/d6071b6236976dcfd469a5175b019a9aeef209f6/scripts/uitest_screenrecord.py).他这个是靠拼接图片实现的视频录制。 这个思路我本地已经复现且可用

**Comment by railsfans** [comment]
我现在想做的其实是通过libusb将ios的视频流获取做相关应用，类似爱思投屏助手应用一样。你提供的github是不断截屏，然后一张张放，跟视频播放一样。
