### ISSUE TITLE
IOS18 MACOS15.0.1找不到设备

### ISSUE THREAD

**Issue by zhang25121** [YueChen-C/ios-screen-record#21]
IOS18 MACOS15.0.1

ioscreen -u 00008030-00030A90C204  record -h264File=/home/out.h264  -wavFile=/home/out.wav

Traceback (most recent call last):
  File "/usr/local/bin/ioscreen", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/ioscreen/main.py", line 56, in main
    args.func(args)
  File "/usr/local/lib/python3.10/site-packages/ioscreen/main.py", line 8, in cmd_record_wav
    device = find_ios_device(args.udid)
  File "/usr/local/lib/python3.10/site-packages/ioscreen/util.py", line 61, in find_ios_device
    raise Exception(f'not find {udid}')
Exception: not find 

TIDEVICE LIST能正常找到设备
UDID                       SerialNumber    NAME    MarketName      ProductVersion  ConnType
00008030-00030A90C204  DNPD90PKN73W    sudu16  iPhone 11                   18  usb

**Comment by YueChen-C** [comment]
不要加 -
